### PR TITLE
Numerous improvements

### PR DESCRIPTION
**Pull request by Splitwirez**
Probably should've made this a series of smaller PRs, please forgive me for getting a bit carried away.

Also, I should note: if this makes it onto NuGet, I would strongly recommend that it be marked as a prerelease version - I'm still a bit hesitant about overall stability, but I've reached the limits of what I can do to ensure stability on my own. I need help hunting down whatever bugs remain, and the only way I can think of to get the help I need at this point is to look to external sources.

### Changelist
- Re-organized some stuff
- `RibbonWindow` is now an actual Window in its own right
- Control size variants are now properties of a control, rather than entirely separate controls
- Added dynamic control size adjustment
- Added `Gallery` control
- Major XAML cleanup
- Switched to using standard Avalonia colours/brushes
- Added `RibbonMenu`
- `Ribbon` can now be collapsed or expanded (shows selected groups temporarily in a `Popup` when a tab is clicked if the `Ribbon` is collapsed)
- `Ribbon` can now be horizontally or vertically oriented (real-time value changes are not yet fully functional, but compile-time/startup-time changes should work without a hitch)
- `KeyTip`s and Keyboard navigation via ALT are now mostly functional
- Probably something else I forgot to mention lol

### CODE REVIEW

**Comment by HankG** [comment]
Really awesome work! Can it still be used without using RibbonWindow as the root?

**Comment by Splitwirez** [comment]
> 
> 
> Really awesome work! Can it still be used without using RibbonWindow as the root?

Thanks :DD

Currently, it should work in a regular Window, yes (and if it somehow doesn't, consider that a bug I'll have to fix). The Quick Access Toolbar could make retaining that option tricky, but...I'll figure something out for that. Hopefully.

**Comment by Splitwirez** [comment]
Due to @amazerol 's...apparent absence, I've decided to move on with AvaloniaRibbon development on my own, from my own fork. If anyone is interested, you can find that here: https://github.com/Splitwirez/AvaloniaRibbon

@amazerol If you ever see this, just know that I hope everything is okay wherever you are, and that you're okay.

**Comment by amazerol** [comment]
I'm fine mate :) I'm very busy with my own company but everything fine ! 
Thank you for moving on with AvaloniaRibbon. Have fun with it.

------ Message d'origine ------
De: "Splitwirez" <notifications@github.com>
À: "amazerol/AvaloniaRibbon" <AvaloniaRibbon@noreply.github.com>
Cc : "Alban Mazerolles" <amazerol_dev@yahoo.com>; "Mention" 
<mention@noreply.github.com>
Envoyé : 06/06/2020 17:36:42
Objet : Re: [amazerol/AvaloniaRibbon] Numerous improvements (#8)

**Pull request merged**
